# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8087

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  localBaseDir: "${HOME}/ItemBank"
  apiVersion: "/api/v4"
  bankKey: "187"

logging:
  level:
    org:
      opentestsystem:
        ap:
          ivs: DEBUG

ivs:
  gitLabSecret: "${GITLAB_WEBHOOK_SECRET}"
  validationQueue: "cpt"
  validationTopicExchange: "cpt-exchange"

---
spring:
  profiles: dev

itembank:
  group: "iat-development"

---
spring:
  profiles: uat

itembank:
  group: "iat-uat"
