# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8087

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  localBaseDir: "${HOME}/ItemBankValidation"
  apiVersion: "/api/v4"
  bankKey: "187"

logging:
  level:
    org:
      opentestsystem:
        ap:
          ivs: DEBUG

ivs:
  gitLabSecret: "secret-key"
  validationQueue: "cpt"
  validationTopicExchange: "cpt-exchange"
  systemUserName: "item-validation-service"
  systemFullName: "Item Validation Service"
  # This path is to the executable version of the CPT appropriate to the machine it's running on.
  # Currently supported environments are Windows (win10-x64), OSX (osx.10.12-x64), and Debian Linux (debian.8-x64).
  # Failure to provide an appropriate executable will cause validation to fail. CPT releases
  # may be found on GitHub here: https://github.com/SmarterApp/TabulateSmarterTestContentPackage/releases
  cptExecutablePath: "/cpt/ContentPackageTabulator"
  #cptExecutablePath: "/Users/gregwhite/Projects/SmarterBalanced/ContentPackageTabulator/ContentPackageTabulator/bin/Release/netcoreapp2.0/osx.10.12-x64/publish/ContentPackageTabulator"


---
spring:
  profiles: dev

itembank:
  group: "iat-development"

---
spring:
  profiles: uat

itembank:
  group: "iat-uat"

---
spring:
  profiles: dev

itembank:
  group: "iat-development"