# Add a Service/Deployment for the AP_ItemValidationService
apiVersion: v1
kind: Service
metadata:
  name: ap-ivs-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ap-ivs
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ap-ivs-deployment
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: ap-ivs
        tier: backend
    spec:
      containers:
      - name: ap-ivs
        image: fwsbac/ap-ivs:@version@
        readinessProbe:
          httpGet:
            path: /manage/health.json
            port: 8080
            scheme: HTTP
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 512M
          limits:
            cpu: 200m
            memory: 1024M
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        - name: JAVA_OPTS
          value: "-Xmx256m"
        ports:
        - containerPort: 8080